### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by dawit-melka**
Completed the navbar it is mobile responsive.

image

image

image

### CODE REVIEW

**Review by Joephy527 — CHANGES_REQUESTED** [review]
on the mobile version the toggle button needs to change from a hamburger icon to a close "X" icon when the menu is opened, the rest looks good, don't forget to be uptodate with the main branch before pushing to the branch and asking for a pull request

**Comment by dawit-melka** [comment]
okay working on it

**Comment by dawit-melka** [comment]
@Joephy527 now the button changes to X when the menu is open.

**Review by Joephy527 — COMMENTED** [review]
Could you add a few comments so that the mobile navigation and the desktop one can be easily identified, also it would be better to use a ternary operator to check the state and display the different icons instead of two && statements.

**Comment by dawit-melka** [comment]
I have added some comments and used ternary operator to check state and display different icons.

**Review by Joephy527 — APPROVED** [review]

**Pull request merged**
