### PR TITLE
About Page Desktop view

### PR DESCRIPTION
**Pull request by dawit-melka**
- I have completed the the desktop view (not responsive) of about page. 
- Note that some of the images used from the asset are distorted which can be changed

**Section 1**
image

**Section 2**
image
image

**Section 3**
image

### CODE REVIEW

**Review by Joephy527 — COMMENTED** [review]
the objectfit prop is deprecated so it's better to use normal css styling to contain the images. 

Also since you have quite a few places that need custom css styles that are outside of the scope of tailwind it's better to use css modules for the components instead of using the style prop everywhere.

Group the static assets of the about page in a folder called about in the images folder.

A better naming convention is also better for the 3 sections, that describes the component a little bit

**Review by nathnaeltefera — CHANGES_REQUESTED** [review]
dave the assets you used on the about page create a folder for them with the same name as your page (aboutpage) other than that everything looks good

**Comment by dawit-melka** [comment]
Comments addressed please check it out.

**Review by nathnaeltefera — APPROVED** [review]
approved!

**Review by Joephy527 — COMMENTED** [review]
In Quest.tsx you've missed one line that needs to be deleted on line 18.

And also try to be consistent with exported function naming either make them all export at the end of file or export them while declaring the functions

**Review by Joephy527 — COMMENTED** [review]
in MissionVisionValues.tsx make the Image self closing

**Review by Joephy527 — APPROVED** [review]
great work!!

**Comment by dawit-melka** [comment]
Thank you for your valuable feedback!

**Comment by Joephy527** [comment]
no problem, we should all help eachother by giving eachother feedback
inorder to improve. Also,  code review is a huge part of the
real-world software job

**Pull request merged**
